name: push
on: [push, deployment]
permissions:
  contents: read
  id-token: write


env:
  BUILD_NUMBER: ${{ github.run_number }}  # used in project file. Version number is 1.0.BUILD_NUMBER

jobs:
  deps:
    uses: uswitch/reusable-actions/.github/workflows/reusable-clojure-deps.yaml@v2
  lint:
    needs: deps
    uses: uswitch/reusable-actions/.github/workflows/reusable-clojure-lint.yaml@v2
  test:
    needs: deps
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      IS_IN_CI: "true"
    steps:
      - run: echo event name ${{ github.event_name }} branch ${{ github.ref_name }}
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: ${{ needs.deps.outputs.deps_path }}
          key: ${{ needs.deps.outputs.hash_key }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
      - uses: DeLaGuardo/setup-clojure@11.0
        with:
          lein: 2.9.1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::136393635417:role/all-internal-jars-readonly
          aws-region: eu-west-1
      # Exit status 143 here would indicate timeout
      - run: timeout --preserve-status 5m lein test
  uberjar:
    needs: deps
    uses: uswitch/reusable-actions/.github/workflows/reusable-clojure-uberjar.yaml@v2
    with:
      jar_file: ./target/
      lein_version: 2.9.1
      distribution: temurin
      java_version: 20
      deps_key: ${{ needs.deps.outputs.hash_key }}
  s3-release:
    if: ${{ github.event_name == 'deployment' || github.ref_name == 'master' }}
    needs:
      - uberjar
      - deps
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        id: restore-deps
        with:
          path: ${{ needs.deps.outputs.deps_path }}
          key: ${{ needs.deps.outputs.hash_key }}
      - uses: actions/cache/restore@v4
        id: restore-jar
        with:
          path: ./target/  # must be IDENTICAL to that passed to uberjar process
          key: ${{ needs.uberjar.outputs.uberjar_hash }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
      - uses: DeLaGuardo/setup-clojure@11.0
        with:
          lein: 2.9.1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_PLATFORM_IT_IAM_ROLE }}
          aws-region: eu-west-1
      - run: lein deploy s3-releases
        id: deploy-jar-to-s3
